apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
        - name: bookstore-backend-pod
          image: achref2h/bookstore-backend:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend-svc
  name: backend-svc
spec:
  selector:
    app: backend-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
