apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
        - name: bookstore-frontend-pod
          image: achref2h/bookstore-frontend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
  metadata:
  labels:
    name: frontend-svc
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: frontend-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
